### ISSUE TITLE
Segmentation fault when compiling on NetBSD

### ISSUE THREAD

**Issue by jaapb** [janestreet/parsexp#1]
When compiling parsexp 0.11.0 on NetBSD/amd64 8.0_RC1, ocamlopt.opt segfaults during the compilation of parsexp at this point:

    ocamlopt src/.parsexp.objs/parsexp__Parser_automaton.{cmx,o} (got signal SEGV)
(cd _build/default && /usr/pkgsrc/devel/ocaml-parsexp/work/.buildlink/bin/ocamlopt.opt -w -40 -safe-string -g -I src/.parsexp.objs -I /usr/pkg/lib/ocaml/site-lib/sexplib0 -no-alias-deps -open Parsexp__ -o src/.parsexp.objs/parsexp__Parser_automaton.cmx -c -impl src/parser_automaton.ml)

This happens both with OCaml 4.06.1 and OCaml 4.07beta2. I tried generating a backtrace, but that seems to be corrupted:
#0  0x0000000000808141 in caml_c_call ()
Backtrace stopped: Cannot access memory at address 0x7f7fff16bfd8

ocamlopt.byte compiles the file with no problem.

I'm not sure how to debug this - happy to run any tests that may be needed.

**Comment by ghost** [comment]
This file uses unsafe features, but it's odd that we get a segfault during compilation. Could you try increasing the stack size to see if it makes a difference? There is a large constant array in this file, it's possible that this is the issue.

**Comment by jaapb** [comment]
Yes, that worked, thanks!
