### ISSUE TITLE
How to locate an error of when analyzing a Sexp.t

### ISSUE THREAD

**Issue by jnavila** [janestreet/parsexp#11]
I can't find a way to find back a position from a given Sexp.t in a root Sexp.t.  Obviously, the positions provided by parsexp are meant to do that, but this is not clear to me.

I'm using a modified version Sexp_decode (https://gitlab.inria.fr/bmontagu/sexp_decode) to parse a Sexp.t made with parsexp; when the decoder fails to decode, I can return the node on which the processing stopped.  Unfortunately, from this node, I can't find a way to trace back to the origin string. 

Is it possible and if so, how?

Thanks

**Comment by aalekseyev** [comment]
Is `Positions.find_sub_sexp_phys` sufficient to do what you want?

```
(** [find_sub_sexp_phys t sexp ~sub] looks for [sub] in [sexp] and return its location,
    assuming [t] is the sequence of positions associated with [sexp].

    Comparison is done using physical equality.
*)
val find_sub_sexp_phys : t -> Sexp.t -> sub:Sexp.t -> range option
```

You can see it being used in `parsexp.ml` to recover the location for error messages, although admittedly the functors make it hard to understand what's going on.

This function relies on there being no sharing between sexp subtrees. If there is sharing, it will point to the first occurrence of the shared sexp, even though the error may want to refer to another occurrence.

**Comment by aalekseyev** [comment]
(feel free to re-open if this doesn't quite address your question)

**Comment by jnavila** [comment]
Thanks! It was clearly visible...
