### ISSUE TITLE
How to use parsexp?

### ISSUE THREAD

**Issue by cogumbreiro** [janestreet/parsexp#2]
Hi, everyone,

I am trying to learn how to use Parsexp. I am sorry if I'm missing the obvious, but I couldn't find a basic example of how to use the library in the README, nor could I find any link to documentation.

Is the source code the only source of documentation?

Thanks for your time.

**Comment by ghost** [comment]
Hi Tiago,

Yes, it's true that a few examples of usage would help. I don't have time to write them at the moment, but here are a few simple example:

- parsing a string containing a single s-expression: `Parsexp.Single.parse_string_exn <string>`
- parsing a string containing a list of s-expressions: `Parsexp.Many.parse_string_exn <string>`
- parsing a string containing a list of s-expressions and converting them to a list of integers (requires ppx_sexp_conv):
```ocaml
Parsexp.Conv_single.parse_string_exn <string> [%of_sexp: int]
```

Hope that helps

**Comment by cogumbreiro** [comment]
Hi Jérémie,

Meanwhile I understood `Sexlib.of_string` was enough for what I needed. I can add an example of using  `Parsexp` in the README if you are interested.

When would you want to use `Parsexp.parse_String_exn` instead of `Sexlib.of_string`?

**Comment by ghost** [comment]
These two functions are quite similar. `Sexplib` is in fact implemented on top of `Parsexp`. The main difference is that the `_exn` suffix of the former makes it clear that the parsing might fail. In real applications, you should use the non `_exn` functions, handle error cases and display them nicely to the user.

**Comment by ghost** [comment]
Closing this PR as there doesn't seem to be anything more to do.
