### ISSUE TITLE
Streaming API / event-based interface?

### ISSUE THREAD

**Issue by cpitclaudel** [janestreet/parsexp#4]
Hi there,

This is related to my previous question (#3): is there a way to use the API ina  streaming manner (that is, to get events every time parsexp sees a new sexp?). This is a common API for XML parsers, and it tens to be more efficient when attempting to extract small amounts of data from large documents.  I imagine this would mean raising exceptions when the parser enters certain states, but since the parser state is opaque in the `Parser_state` interface this seems non-obvious to do without changing the library.  Did I miss something, , and if not would it take a lot of work to extend the library to enable streaming parsing?

Thanks!

**Comment by aalekseyev** [comment]
Indeed the Eager parser interface is a supported way to consume s-expressions one-by-one.

Please have a look at the `Parsexp.Eager` module and an example [here](https://github.com/janestreet/parsexp/blob/master/src/parser_intf.ml#L72).

As an example that definitely works, we use the eager interface to implement a continuation-based parser in sexplib (see https://github.com/janestreet/sexplib/blob/master/src/pre_sexp.ml).

**Comment by cpitclaudel** [comment]
Thanks, I thought I had looked at the Eager parser, but I had concluded it didn't do what I needed.

To be clear, I don't want want to consume sexps one by one; I want to parse things partial input like `(((a b) (c`  — is that what the eager parser does?

**Comment by aalekseyev** [comment]
Sorry, I must have misread the question. The Eager parser only gives you complete sexps. It does not give you any partial sexps.

Indeed exposing a more expressive API would be necessary to retrieve the partial sexps. I don't have a concrete idea of what that API should look like, though.

**Comment by cpitclaudel** [comment]
I think the type of streaming APIs used in XML parsers would work perfectly here.
