### ISSUE TITLE
0.14.1 fails to build with ocaml-4.12.0: Library "base.caml" not found.

### ISSUE THREAD

**Issue by yurivict** [janestreet/parsexp#8]
```
File "src/dune", line 1, characters 66-75:
1 | (library (name parsexp) (public_name parsexp) (libraries sexplib0 base.caml)
                                                                      ^^^^^^^^^
Error: Library "base.caml" not found.
Hint: try:
  dune external-lib-deps --missing @@default
```

OS: FreeBSD 13

**Comment by aalekseyev** [comment]
I'm guessing there's a problem with how the packages are used together.
At least in base 0.14.1 I can see there is a library base.caml:

https://github.com/janestreet/base/blob/e9dc05f5ca7a5a995e95d8617a12b0ecb4f5408b/compiler-stdlib/src/dune

Maybe you're not using the right version of base, or the build system is not seeing it for some reason.
